server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product_api?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

aws:
  region: us-east-1
  sns-topic:
    product-events-arn: product-events
  s3:
    bucket:
      invoice-name: pcs-invoice
  sqs:
    queue:
      invoice:
        events-name: s3-invoice-events